#!/usr/bin/env python3
"""
Processes atmospheric profiles with PICASO for full radiative transfer.

This script reads profile data from HDF5 files (generated by create_profiles.py or
convert_roth.py), runs them through the PICASO radiative transfer model to compute
fluxes, and saves the combined input parameters and output results into a single
final HDF5 dataset. It is the final step of the data generation pipeline.
"""

import os
import logging
import json
from pathlib import Path
import numpy as np
import pandas as pd
import h5py
from tqdm import tqdm
from astropy import constants as const

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logging.getLogger("numba").setLevel(logging.WARNING)

# --- Physical Constants and Reference Values (using astropy.constants) ---
JUPITER_RADIUS_M = const.R_jup.value
JUPITER_MASS_KG = const.M_jup.value
SOLAR_RADIUS_M = const.R_sun.value
AU_TO_METERS = const.au.value

# --- Configuration for file paths and PICASO settings ---
PICASO_CONFIG = {
    "input_hdf5_files": ["synthetic_profiles.h5"],
    "output_hdf5_file": "picaso_results.h5",
    "picaso_refdata_path": "../reference/",
    "pysyn_cdbs_path": "../grp/redcat/trds/",
    "opacity_database_file": "../sonora_2020_feh+000_co_100.data.196"
}

# Set environment variables for PICASO before it's imported
os.environ['picaso_refdata'] = PICASO_CONFIG["picaso_refdata_path"]
os.environ['PYSYN_CDBS'] = PICASO_CONFIG["pysyn_cdbs_path"]


def run_picaso_for_profile(profile_data, picaso_deps):
    """
    Runs a PICASO simulation for a single atmospheric profile.

    Parameters:
    -----------
    profile_data : dict
        A dictionary containing all parameters and the T-P profile from a JSON file.
    picaso_deps : dict
        A dictionary containing pre-initialized PICASO objects (e.g., opacity db).

    Returns:
    --------
    picaso_results : dict
        A dictionary with the calculated flux arrays.
    """
    jdi = picaso_deps['jdi']
    opacity_db = picaso_deps['opacity_db']

    case = jdi.inputs()
    case.approx(get_lvl_flux=True)
    case.phase_angle(0)

    # Set planet properties
    case.gravity(
        radius=profile_data["planet_radius_m"] / JUPITER_RADIUS_M,
        radius_unit=jdi.u.Unit("R_jup"),
        mass=profile_data["planet_mass_kg"] / JUPITER_MASS_KG,
        mass_unit=jdi.u.Unit("M_jup")
    )

    # Set star properties, using the pre-calculated orbital distance from the JSON file
    case.star(
        opacity_db,
        profile_data["star_temperature_k"],
        profile_data["star_metallicity"],
        profile_data["star_logg"],
        database="phoenix",
        radius=profile_data["star_radius_m"] / SOLAR_RADIUS_M,
        radius_unit=jdi.u.Unit("R_sun"),
        semi_major=profile_data["orbital_distance_m"] / AU_TO_METERS,
        semi_major_unit=jdi.u.Unit("au")
    )

    # Set atmosphere from the input T-P profile
    case.atmosphere(df=pd.DataFrame({
        "pressure": profile_data["pressure_bar"],
        "temperature": profile_data["temperature_k"]
    }))

    # Run chemistry
    case.premix_atmosphere(
        opacity_db,
        df=case.inputs['atmosphere']['profile'].loc[:, ['pressure', 'temperature']]
    )

    # Calculate spectrum and fluxes
    picaso_output = case.spectrum(
        opacity_db, full_output=True, calculation="thermal+reflected"
    )

    # Extract level-resolved fluxes and wavenumber widths
    level_data = picaso_output['full_output']['level']
    delta_wno = opacity_db.delta_wno

    # 1. Integrate THERMAL fluxes (spectral density) by multiplying by delta_wno
    thermal_plus = level_data['thermal_fluxes']['flux_plus']
    thermal_minus = level_data['thermal_fluxes']['flux_minus']
    net_thermal = np.sum((thermal_plus - thermal_minus) * delta_wno, axis=1)

    # 2. Sum REFLECTED fluxes (already pre-integrated per bin) WITHOUT multiplying by delta_wno
    # This is a quirk of PICASO in THIS CURRENT VERSION!!!!!
    reflected_plus = level_data['reflected_fluxes']['flux_plus']
    reflected_minus = level_data['reflected_fluxes']['flux_minus']
    net_reflected = np.sum(reflected_plus - reflected_minus, axis=1)

    return {
        "pressure_bar_picaso": level_data["pressure"],
        "net_thermal_flux": net_thermal,
        "net_reflected_flux": net_reflected
    }


def main():
    """Main execution function to drive the PICASO simulations."""
    # Initialize PICASO
    try:
        import picaso.justdoit as jdi_module
        opacity_db = jdi_module.opannection(ck=True, ck_db=PICASO_CONFIG["opacity_database_file"])
        picaso_dependencies = {'jdi': jdi_module, 'opacity_db': opacity_db}
        logging.info("PICASO imported and configured successfully.")
    except Exception as e:
        logging.critical(f"Failed to initialize PICASO. Please check paths. Error: {e}", exc_info=True)
        return

    # Find and count profiles in input HDF5 files
    input_files = [Path(f) for f in PICASO_CONFIG["input_hdf5_files"] if Path(f).exists()]
    if not input_files:
        logging.critical("No valid input HDF5 files found. Checked: " + ", ".join(PICASO_CONFIG["input_hdf5_files"]))
        return

    logging.info(f"Found {len(input_files)} input HDF5 files to process.")
    total_profiles = 0
    first_valid_file = None
    for f_path in input_files:
        try:
            with h5py.File(f_path, 'r') as hf:
                count = hf['pressure_bar'].shape[0]
                if count > 0:
                    total_profiles += count
                    if first_valid_file is None:
                        first_valid_file = f_path
        except Exception as e:
            logging.warning(f"Could not read profiles from {f_path}. Skipping. Error: {e}")

    if total_profiles == 0:
        logging.critical("No profiles found across all specified HDF5 files. Aborting.")
        return
    logging.info(f"Found a total of {total_profiles} profiles to process.")

    # Clean up old output file
    output_path = Path(PICASO_CONFIG["output_hdf5_file"])
    if output_path.exists():
        logging.info(f"Removing existing output file: {output_path}")
        output_path.unlink()

    # Dry run on the first profile to determine HDF5 schema
    logging.info(f"Performing dry run with first profile from '{first_valid_file}' to determine schema...")
    try:
        with h5py.File(first_valid_file, 'r') as hf:
            keys = list(hf.keys())
            first_profile_data = {key: hf[key][0] for key in keys}
        picaso_results = run_picaso_for_profile(first_profile_data, picaso_dependencies)
        full_result_schema = {**first_profile_data, **picaso_results}
        logging.info("Dry run successful. Schema determined.")
    except Exception as e:
        logging.critical(f"Dry run failed on first profile. Aborting. Error: {e}", exc_info=True)
        return

    # Create HDF5 file and datasets
    with h5py.File(output_path, 'w') as hf_out:
        hf_out.attrs['picaso_config'] = json.dumps(PICASO_CONFIG)
        datasets = {}
        for key, value in full_result_schema.items():
            value_np = np.array(value)
            shape = (total_profiles,) + value_np.shape
            # Use float32 for floats to save space, but respect other types like bool
            dtype = np.float32 if value_np.dtype.kind == 'f' else value_np.dtype
            datasets[key] = hf_out.create_dataset(
                key, shape, dtype=dtype, compression="gzip", compression_opts=4
            )

        # Process all profiles and save to HDF5
        success_count = 0
        with tqdm(total=total_profiles, desc="Running PICASO Simulations") as pbar:
            for file_path in input_files:
                try:
                    with h5py.File(file_path, 'r') as hf_in:
                        pbar.set_description(f"Processing {file_path.name}")
                        num_in_file = hf_in['pressure_bar'].shape[0]
                        if num_in_file == 0: continue

                        keys = list(hf_in.keys())
                        for i in range(num_in_file):
                            try:
                                profile_data = {key: hf_in[key][i] for key in keys}
                                picaso_results = run_picaso_for_profile(profile_data, picaso_dependencies)
                                full_result = {**profile_data, **picaso_results}

                                for key, value in full_result.items():
                                    if key in datasets:
                                        datasets[key][success_count] = value
                                success_count += 1
                            except Exception as e:
                                logging.warning(f"Failed profile {i} in {file_path.name}. Skipping. Error: {e}")
                            pbar.update(1)
                except Exception as e:
                    logging.error(f"Could not process file {file_path}. Skipping file. Error: {e}")
                    # Fast-forward progress bar if a whole file fails
                    try:
                        with h5py.File(file_path, 'r') as hf_in: pbar.update(hf_in['pressure_bar'].shape[0])
                    except: pass # Ignore if file is unreadable

        logging.info(f"Successfully processed {success_count}/{total_profiles} profiles.")
        if success_count < total_profiles and success_count > 0:
            logging.info(f"Trimming HDF5 datasets to size {success_count}.")
            for key in datasets:
                hf_out[key].resize((success_count,) + hf_out[key].shape[1:])
        elif success_count == 0:
             logging.error("No profiles were successfully processed. HDF5 file will be empty or incomplete.")

    logging.info("HDF5 generation complete!")
    if output_path.exists():
        file_size_mb = output_path.stat().st_size / (1024**2)
        logging.info(f"Created HDF5 file: {output_path} ({file_size_mb:.1f} MB)")


if __name__ == "__main__":
    main()